apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-lab.fullname" . }}-service
  namespace: devops-lab
  labels:
    {{- include "devops-lab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "devops-lab.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
